local addon, ns = ...
local CheckMyMacrosUI = ns.CheckMyMacrosUI

local keybindTable = {
--- S1-S0填指向类技能 A1-C0 填不用指向类的技能
--WS
["MONK"] = {
		["酒仙"] = {
			["A1"] = "醉酿投",
			["A2"] = "猛虎掌",
			["A3"] = "火焰之息",
			["A4"] = "移花接木",
			["A5"] = "金创药",
			["A6"] = "幻灭猛击",
			["A7"] = "真气波",
			["A8"] = "真气爆裂",
			["A9"] = "碧玉疾风",
			["A0"] = "铁骨酒",
			["C1"] = "活血酒",
			["C2"] = "玄牛酒",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["踏风"] = {
			["A1"] = "旭日东升踢",
			["A2"] = "猛虎掌",
			["A3"] = "怒雷破",
			["A4"] = "反向伤害",
			["A5"] = "升龙霸",
			["A6"] = "幻灭踢",
			["A7"] = "真气波",
			["A8"] = "真气爆裂",
			["A9"] = "碧玉疾风",
			["A0"] = "白虎拳",
			["C1"] = "神鹤引项踢",
			["C2"] = "豪能酒",
			["C3"] = "无",
			["C4"] = "白虎下凡",
			["C5"] = "轮回之触",
			["C6"] = "风火雷电",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["织雾"] = {
			["A1"] = "旭日东升踢",
			["A2"] = "猛虎掌",
			["A3"] = "抚慰之雾",
			["A4"] = "复苏之雾",
			["A5"] = "氤氲之雾",
			["A6"] = "幻灭踢",
			["A7"] = "真气波",
			["A8"] = "真气爆裂",
			["A9"] = "碧愈疾风",
			["A0"] = "朱鹤赤精",
			["C1"] = "神鹤引项踢",
			["C2"] = "还魂术",
			["C3"] = "无",
			["C4"] = "活血术",
			["C5"] = "精华之泉",
			["C6"] = "作茧缚命",
			["C7"] = "升腾之雾",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},
--DH
["DEMONHUNTER"] = {
		["浩劫"] = {
			["A1"] = "恶魔变形",
			["A2"] = "涅墨西斯",
			["A3"] = "黑暗鞭挞",
			["A4"] = "混乱打击",
			["A5"] = "刃舞",
			["A6"] = "眼棱",
			["A7"] = "邪能弹幕",
			["A8"] = "献祭光环",
			["A9"] = "邪能之刃",
			["A0"] = "恶魔之咬",
			["C1"] = "投掷利刃",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["复仇"] = {
			["A1"] = "恶魔变形",
			["A2"] = "烈火烙印",
			["A3"] = "烈焰咒符",
			["A4"] = "灵魂裂劈",
			["A5"] = "裂魂",
			["A6"] = "恶魔尖刺",
			["A7"] = "幽魂炸弹",
			["A8"] = "献祭光环",
			["A9"] = "邪能之刃",
			["A0"] = "无",
			["C1"] = "投掷利刃",
			["C2"] = "邪能毁灭",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
			
},
--LR
["HUNTER"] = {
		["野兽控制"] = {
			["A1"] = "野性守护",
			["A2"] = "狂野怒火",
			["A3"] = "倒刺射击",
			["A4"] = "多重射击",
			["A5"] = "群兽奔腾",
			["A6"] = "奇美拉射击",
			["A7"] = "夺命黑鸦",
			["A8"] = "弹幕射击",
			["A9"] = "杀戮命令",
			["A0"] = "凶暴野兽",
			["C1"] = "眼镜蛇射击",
			["C2"] = "喷毒眼镜蛇",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["射击"] = {
			["A1"] = "百发百中",
			["A2"] = "瞄准射击",
			["A3"] = "猎人印记",
			["A4"] = "多重射击",
			["A5"] = "二连发",
			["A6"] = "爆炸射击",
			["A7"] = "夺命黑鸦",
			["A8"] = "弹幕射击",
			["A9"] = "急速射击",
			["A0"] = "毒蛇钉刺",
			["C1"] = "奥术射击",
			["C2"] = "穿刺射击",
			["C3"] = "无",
			["C4"] = "稳固射击",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["生存"] = {
			["A1"] = "雄鹰守护",
			["A2"] = "协同进攻",
			["A3"] = "猛禽一击",
			["A4"] = "无",
			["A5"] = "侧翼打击",
			["A6"] = "野火炸弹",
			["A7"] = "夺命黑鸦",
			["A8"] = "飞轮",
			["A9"] = "杀戮命令",
			["A0"] = "毒蛇钉刺",
			["C1"] = "削凿",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},		
		
},
--QS
["PALADIN"] = {
		["防护"] = {
			["A1"] = "复仇之怒",
			["A2"] = "复仇者之盾",
			["A3"] = "炽天使",
			["A4"] = "正义盾击",
			["A5"] = "圣光壁垒",
			["A6"] = "守护之光",
			["A7"] = "审判",
			["A8"] = "正义之锤",
			["A9"] = "奉献",
			["A0"] = "十字军打击",
			["C1"] = "处决宣判",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["惩戒"] = {
			["A1"] = "复仇之怒",
			["A2"] = "异端裁决",
			["A3"] = "神圣风暴",
			["A4"] = "圣殿骑士的裁决",
			["A5"] = "灰烬觉醒",
			["A6"] = "公正之剑",
			["A7"] = "审判",
			["A8"] = "愤怒之锤",
			["A9"] = "奉献",
			["A0"] = "十字军打击",
			["C1"] = "处决宣判",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["神圣"] = {
			["A1"] = "复仇之怒",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "审判",
			["A8"] = "无",
			["A9"] = "奉献",
			["A0"] = "十字军打击",
			["C1"] = "神圣震击",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},		
		
},
--DZ
["ROGUE"] = {
		["奇袭"] = {
			["A1"] = "致命药膏",
			["A2"] = "消失",
			["A3"] = "减速药膏",
			["A4"] = "宿敌",
			["A5"] = "刀扇",
			["A6"] = "死亡标记",
			["A7"] = "割裂",
			["A8"] = "毁伤",
			["A9"] = "毒伤",
			["A0"] = "淬毒之刃",
			["C1"] = "锁喉",
			["C2"] = "抽血",
			["C3"] = "无",
			["C4"] = "潜行",
			["C5"] = "天降杀机",
			["C6"] = "猩红风暴",
			["C7"] = "侧袭",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["狂徒"] = {
			["A1"] = "鬼魅攻击",
			["A2"] = "消失",
			["A3"] = "命运骨骰",
			["A4"] = "冲动",
			["A5"] = "剑刃乱舞",
			["A6"] = "死亡标记",
			["A7"] = "斩击",
			["A8"] = "影袭",
			["A9"] = "正中眉心",
			["A0"] = "刀锋冲刺",
			["C1"] = "影舞步",
			["C2"] = "手枪射击",
			["C3"] = "无",
			["C4"] = "潜行",
			["C5"] = "天降杀机",
			["C6"] = "伏击",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["敏锐"] = {
			["A1"] = "死亡符记",
			["A2"] = "消失",
			["A3"] = "暗影之舞",
			["A4"] = "暗影之刃",
			["A5"] = "袖剑风暴",
			["A6"] = "死亡标记",
			["A7"] = "袖剑旋风",
			["A8"] = "暗影打击",
			["A9"] = "刺骨",
			["A0"] = "背刺",
			["C1"] = "影分身",
			["C2"] = "夜刃",
			["C3"] = "无",
			["C4"] = "潜行",
			["C5"] = "天降杀机",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},
--SS
["WARLOCK"] = {
		["毁灭"] = {
			["A1"] = "烧尽",
			["A2"] = "混乱之箭",
			["A3"] = "献祭",
			["A4"] = "燃烧",
			["A5"] = "大灾变",
			["A6"] = "黑暗灵魂：动荡",
			["A7"] = "召唤地狱火",
			["A8"] = "恶魔之火",
			["A9"] = "灵魂之火",
			["A0"] = "火焰之雨",
			["C1"] = "浩劫",
			["C2"] = "暗影灼烧",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "吸取生命",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["恶魔学识"] = {
			["A1"] = "古尔丹之手",
			["A2"] = "恶魔之箭",
			["A3"] = "召唤邪犬",
			["A4"] = "内爆",
			["A5"] = "召唤恐惧猎犬",
			["A6"] = "魔典：恶魔卫士",
			["A7"] = "召唤恶魔暴君",
			["A8"] = "灾怨轰炸",
			["A9"] = "厄运",
			["A0"] = "能量虹吸",
			["C1"] = "恶魔力量",
			["C2"] = "灵魂打击",
			["C3"] = "无",
			["C4"] = "暗影箭",
			["C5"] = "虚空传送门",
			["C6"] = "吸取生命",
			["C7"] = "召唤恶魔卫士",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["痛苦"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},
--ZS
["WARRIOR"] = {
		["武器"] = {
			["A1"] = "剑刃风暴",
			["A2"] = "巨人打击",
			["A3"] = "碎颅打击",
			["A4"] = "撕裂",
			["A5"] = "战斗怒吼",
			["A6"] = "压制",
			["A7"] = "斩杀",
			["A8"] = "旋风斩",
			["A9"] = "横扫攻击",
			["A0"] = "猛击",
			["C1"] = "致死打击",
			["C2"] = "灭战者",
			["C3"] = "无",
			["C4"] = "顺劈斩",
			["C5"] = "天神下凡",
			["C6"] = "致命平静",
			["C7"] = "破坏者",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "乘胜追击",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["狂怒"] = {
			["A1"] = "剑刃风暴",
			["A2"] = "巨龙怒吼",
			["A3"] = "怒击",
			["A4"] = "破城者",
			["A5"] = "战斗怒吼",
			["A6"] = "嗜血",
			["A7"] = "斩杀",
			["A8"] = "旋风斩",
			["A9"] = "暴怒",
			["A0"] = "鲁莽",
			["C1"] = "狂暴挥砍",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "乘胜追击",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["防护"] = {
			["A1"] = "挫志怒吼",
			["A2"] = "巨龙怒吼",
			["A3"] = "无视苦痛",
			["A4"] = "雷霆一击",
			["A5"] = "战斗怒吼",
			["A6"] = "破坏者",
			["A7"] = "盾牌格挡",
			["A8"] = "毁灭打击",
			["A9"] = "盾牌猛击",
			["A0"] = "复仇",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "天神下凡",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "乘胜追击",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},

--SM
["SHAMAN"] = {
		["增强"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["元素"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["恢复"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},
--DK
["DEATHKNIGHT"] = {
		["鲜血"] = {
			["A1"] = "符文刃舞",
			["A2"] = "墓石",
			["A3"] = "灵界打击",
			["A4"] = "饮血者",
			["A5"] = "骨髓分裂",
			["A6"] = "血液沸腾",
			["A7"] = "白骨风暴",
			["A8"] = "枯萎凋零",
			["A9"] = "符文打击",
			["A0"] = "心脏打击",
			["C1"] = "吞噬",
			["C2"] = "死神的抚摩",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["冰霜"] = {
			["A1"] = "凛风冲击",
			["A2"] = "冰川突进",
			["A3"] = "冰霜打击",
			["A4"] = "寒冰联结",
			["A5"] = "冰霜之柱",
			["A6"] = "冰龙吐息",
			["A7"] = "符文武器增效",
			["A8"] = "冰霜巨龙之怒",
			["A9"] = "寒冰锁链",
			["A0"] = "湮灭",
			["C1"] = "冷酷严冬",
			["C2"] = "冰霜之镰",
			["C3"] = "无",
			["C4"] = "寒冬号角",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["邪恶"] = {
			["A1"] = "亡者复生",
			["A2"] = "爆发",
			["A3"] = "凋零缠绕",
			["A4"] = "脓疮打击",
			["A5"] = "天灾打击",
			["A6"] = "灵界打击",
			["A7"] = "枯萎凋零",
			["A8"] = "黑暗突变",
			["A9"] = "天启",
			["A0"] = "亡者大军",
			["C1"] = "暗影之爪",
			["C2"] = "邪恶虫群",
			["C3"] = "无",
			["C4"] = "灵魂收割",
			["C5"] = "亵渎",
			["C6"] = "传染",
			["C7"] = "邪恶狂乱",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "召唤石像鬼",
			["C0"] = "培育憎恶",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},		
		
},
--FS
["MAGE"] = {
		["冰霜"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["火焰"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["奥术"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},		
		
},
--MS
["PRIEST"] = {
		["暗影"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["戒律"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["神圣"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},		
		
},
--DLY
["DRUID"] = {
		["平衡"] = {
			["A1"] = "枭兽形态",
			["A2"] = "阳炎之怒",
			["A3"] = "星涌术",
			["A4"] = "艾露恩的战士",
			["A5"] = "激活",
			["A6"] = "自然之力",
			["A7"] = "化身：艾露恩之眷",
			["A8"] = "超凡之盟",
			["A9"] = "艾露恩之怒",
			["A0"] = "星辰坠落",
			["C1"] = "阳炎术",
			["C2"] = "月火术",
			["C3"] = "无",
			["C4"] = "新月",
			["C5"] = "明月打击",
			["C6"] = "星辰耀斑",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},
		["野性"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",			
		},
		["守护"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},		

		["恢复"] = {
			["A1"] = "无",
			["A2"] = "无",
			["A3"] = "无",
			["A4"] = "无",
			["A5"] = "无",
			["A6"] = "无",
			["A7"] = "无",
			["A8"] = "无",
			["A9"] = "无",
			["A0"] = "无",
			["C1"] = "无",
			["C2"] = "无",
			["C3"] = "无",
			["C4"] = "无",
			["C5"] = "无",
			["C6"] = "无",
			["C7"] = "无",
			["C8"] = "艾泽拉斯之心精华",
			["C9"] = "无",
			["C0"] = "无",
			["S1"] = "无",
			["S2"] = "无",
			["S3"] = "无",
			["S4"] = "无",
			["S5"] = "无",
			["S6"] = "无",
			["S7"] = "无",
			["S8"] = "无",
			["S9"] = "无",
			["S0"] = "无",				
		},	
		
},



}

local function Spell_Key(key)

local Class = select(2, UnitClass("player"))
local Special = select(2, GetSpecializationInfo(GetSpecialization()))

local SPRLL = keybindTable[Class][Special][key]
return SPRLL

end



local function CreateMacros()


local Spell_Key = Spell_Key

local MacroSwith1 = GetMacroInfo("PD_大招开关")
local MacroSwith2 = GetMacroInfo("PD_单体开关")
local MacroSwith3 = GetMacroInfo("PD_暂停")
--local MacroSwith4 = GetMacroInfo(Spell_Key("C3"))
--local MacroSwith5 = GetMacroInfo(Spell_Key("C8"))

local Common,Role = GetNumMacros()

--创建宏
if Common < 120 then 
--开关宏
if MacroSwith1 == nil then CreateMacro("PD_大招开关",574570,"/PD CCD") end
if MacroSwith2 == nil then CreateMacro("PD_单体开关",574570,"/PD AOE") end
if MacroSwith3 == nil then CreateMacro("PD_暂停",574570,"/PD AUTO") end
--if MacroSwith4 == nil then CreateMacro(Spell_Key("C3"),574570,[[/use 远程拾取器
--/stopcasting]])    
--end
--if MacroSwith5 == nil then CreateMacro(Spell_Key("C8"),574570,"/cast [nochanneling] 艾泽拉斯之心精华") end


end

end



local function  CleanKEY()
local Spell_Key = Spell_Key
--初始化清除按键
if GetBindingAction("NUMPAD1") ~= "SPELL "..Spell_Key("A1") then SetBinding("NUMPAD1") end
if GetBindingAction("NUMPAD2") ~= "SPELL "..Spell_Key("A2") then SetBinding("NUMPAD2") end
if GetBindingAction("NUMPAD3") ~= "SPELL "..Spell_Key("A3") then SetBinding("NUMPAD3") end
if GetBindingAction("NUMPAD4") ~= "SPELL "..Spell_Key("A4") then SetBinding("NUMPAD4") end
if GetBindingAction("NUMPAD5") ~= "SPELL "..Spell_Key("A5") then SetBinding("NUMPAD5") end
if GetBindingAction("NUMPAD6") ~= "SPELL "..Spell_Key("A6") then SetBinding("NUMPAD6") end
if GetBindingAction("NUMPAD7") ~= "SPELL "..Spell_Key("A7") then SetBinding("NUMPAD7") end
if GetBindingAction("NUMPAD8") ~= "SPELL "..Spell_Key("A8") then SetBinding("NUMPAD8") end
if GetBindingAction("NUMPAD9") ~= "SPELL "..Spell_Key("A9") then SetBinding("NUMPAD9") end
if GetBindingAction("NUMPAD0") ~= "SPELL "..Spell_Key("A0") then SetBinding("NUMPAD0") end

if GetBindingAction("CTRL-NUMPAD1") ~= "SPELL "..Spell_Key("C1") then SetBinding("CTRL-NUMPAD1") end
if GetBindingAction("CTRL-NUMPAD2") ~= "SPELL "..Spell_Key("C2") then SetBinding("CTRL-NUMPAD2") end
if GetBindingAction("CTRL-NUMPAD3") ~= "SPELL "..Spell_Key("C3") then SetBinding("CTRL-NUMPAD3") end
if GetBindingAction("CTRL-NUMPAD4") ~= "SPELL "..Spell_Key("C4") then SetBinding("CTRL-NUMPAD4") end
if GetBindingAction("CTRL-NUMPAD5") ~= "SPELL "..Spell_Key("C5") then SetBinding("CTRL-NUMPAD5") end
if GetBindingAction("CTRL-NUMPAD6") ~= "SPELL "..Spell_Key("C6") then SetBinding("CTRL-NUMPAD6") end
if GetBindingAction("CTRL-NUMPAD7") ~= "SPELL "..Spell_Key("C7") then SetBinding("CTRL-NUMPAD7") end
if GetBindingAction("CTRL-NUMPAD8") ~= "SPELL "..Spell_Key("C8") then SetBinding("CTRL-NUMPAD8") end
if GetBindingAction("CTRL-NUMPAD9") ~= "SPELL "..Spell_Key("C9") then SetBinding("CTRL-NUMPAD9") end
if GetBindingAction("CTRL-NUMPAD0") ~= "SPELL "..Spell_Key("C0") then SetBinding("CTRL-NUMPAD0") end


if GetBindingAction("ALT-NUMPAD1") ~= "SPELL "..Spell_Key("S1") then SetBinding("ALT-NUMPAD1") end
if GetBindingAction("ALT-NUMPAD2") ~= "SPELL "..Spell_Key("S2") then SetBinding("ALT-NUMPAD2") end
if GetBindingAction("ALT-NUMPAD3") ~= "SPELL "..Spell_Key("S3") then SetBinding("ALT-NUMPAD3") end
if GetBindingAction("ALT-NUMPAD4") ~= "SPELL "..Spell_Key("S4") then SetBinding("ALT-NUMPAD4") end
if GetBindingAction("ALT-NUMPAD5") ~= "SPELL "..Spell_Key("S5") then SetBinding("ALT-NUMPAD5") end
if GetBindingAction("ALT-NUMPAD6") ~= "SPELL "..Spell_Key("S6") then SetBinding("ALT-NUMPAD6") end
if GetBindingAction("ALT-NUMPAD7") ~= "SPELL "..Spell_Key("S7") then SetBinding("ALT-NUMPAD7") end
if GetBindingAction("ALT-NUMPAD8") ~= "SPELL "..Spell_Key("S8") then SetBinding("ALT-NUMPAD8") end
if GetBindingAction("ALT-NUMPAD9") ~= "SPELL "..Spell_Key("S9") then SetBinding("ALT-NUMPAD9") end
if GetBindingAction("ALT-NUMPAD0") ~= "SPELL "..Spell_Key("S0") then SetBinding("ALT-NUMPAD0") end


end

local function SetKEY()
local Spell_Key = Spell_Key
--按键绑定

if GetBindingAction("NUMPAD1") ~= "SPELL "..Spell_Key("A1") then SetBindingSpell("NUMPAD1",Spell_Key("A1")) end
if GetBindingAction("NUMPAD2") ~= "SPELL "..Spell_Key("A2") then SetBindingSpell("NUMPAD2",Spell_Key("A2"))	end
if GetBindingAction("NUMPAD3") ~= "SPELL "..Spell_Key("A3") then SetBindingSpell("NUMPAD3",Spell_Key("A3")) end
if GetBindingAction("NUMPAD4") ~= "SPELL "..Spell_Key("A4") then SetBindingSpell("NUMPAD4",Spell_Key("A4")) end
if GetBindingAction("NUMPAD5") ~= "SPELL "..Spell_Key("A5") then SetBindingSpell("NUMPAD5",Spell_Key("A5"))	end
if GetBindingAction("NUMPAD6") ~= "SPELL "..Spell_Key("A6") then SetBindingSpell("NUMPAD6",Spell_Key("A6")) end
if GetBindingAction("NUMPAD7") ~= "SPELL "..Spell_Key("A7") then SetBindingSpell("NUMPAD7",Spell_Key("A7")) end
if GetBindingAction("NUMPAD8") ~= "SPELL "..Spell_Key("A8") then SetBindingSpell("NUMPAD8",Spell_Key("A8")) end
if GetBindingAction("NUMPAD9") ~= "SPELL "..Spell_Key("A9") then SetBindingSpell("NUMPAD9",Spell_Key("A9")) end
if GetBindingAction("NUMPAD0") ~= "SPELL "..Spell_Key("A0") then SetBindingSpell("NUMPAD0",Spell_Key("A0")) end

if GetBindingAction("CTRL-NUMPAD1") ~= "SPELL "..Spell_Key("C1") then SetBindingSpell("CTRL-NUMPAD1",Spell_Key("C1")) end
if GetBindingAction("CTRL-NUMPAD2") ~= "SPELL "..Spell_Key("C2") then SetBindingSpell("CTRL-NUMPAD2",Spell_Key("C2")) end
if GetBindingAction("CTRL-NUMPAD3") ~= "SPELL "..Spell_Key("C3") then SetBindingSpell("CTRL-NUMPAD3",Spell_Key("C3")) end
if GetBindingAction("CTRL-NUMPAD4") ~= "SPELL "..Spell_Key("C4") then SetBindingSpell("CTRL-NUMPAD4",Spell_Key("C4")) end
if GetBindingAction("CTRL-NUMPAD5") ~= "SPELL "..Spell_Key("C5") then SetBindingSpell("CTRL-NUMPAD5",Spell_Key("C5")) end
if GetBindingAction("CTRL-NUMPAD6") ~= "SPELL "..Spell_Key("C6") then SetBindingSpell("CTRL-NUMPAD6",Spell_Key("C6")) end
if GetBindingAction("CTRL-NUMPAD7") ~= "SPELL "..Spell_Key("C7") then SetBindingSpell("CTRL-NUMPAD7",Spell_Key("C7")) end
if GetBindingAction("CTRL-NUMPAD8") ~= "SPELL "..Spell_Key("C8") then SetBindingSpell("CTRL-NUMPAD8",Spell_Key("C8")) end
if GetBindingAction("CTRL-NUMPAD9") ~= "SPELL "..Spell_Key("C9") then SetBindingSpell("CTRL-NUMPAD9",Spell_Key("C9")) end
if GetBindingAction("CTRL-NUMPAD0") ~= "SPELL "..Spell_Key("C0") then SetBindingSpell("CTRL-NUMPAD0",Spell_Key("C0")) end


if GetBindingAction("ALT-NUMPAD1") ~= "SPELL "..Spell_Key("S1") then SetBindingSpell("ALT-NUMPAD1",Spell_Key("S1")) end
if GetBindingAction("ALT-NUMPAD2") ~= "SPELL "..Spell_Key("S2") then SetBindingSpell("ALT-NUMPAD2",Spell_Key("S2")) end
if GetBindingAction("ALT-NUMPAD3") ~= "SPELL "..Spell_Key("S3") then SetBindingSpell("ALT-NUMPAD3",Spell_Key("S3")) end
if GetBindingAction("ALT-NUMPAD4") ~= "SPELL "..Spell_Key("S4") then SetBindingSpell("ALT-NUMPAD4",Spell_Key("S4")) end
if GetBindingAction("ALT-NUMPAD5") ~= "SPELL "..Spell_Key("S5") then SetBindingSpell("ALT-NUMPAD5",Spell_Key("S5")) end
if GetBindingAction("ALT-NUMPAD6") ~= "SPELL "..Spell_Key("S6") then SetBindingSpell("ALT-NUMPAD6",Spell_Key("S6")) end
if GetBindingAction("ALT-NUMPAD7") ~= "SPELL "..Spell_Key("S7") then SetBindingSpell("ALT-NUMPAD7",Spell_Key("S7")) end
if GetBindingAction("ALT-NUMPAD8") ~= "SPELL "..Spell_Key("S8") then SetBindingSpell("ALT-NUMPAD8",Spell_Key("S8")) end
if GetBindingAction("ALT-NUMPAD9") ~= "SPELL "..Spell_Key("S9") then SetBindingSpell("ALT-NUMPAD9",Spell_Key("S9")) end
if GetBindingAction("ALT-NUMPAD0") ~= "SPELL "..Spell_Key("S0") then SetBindingSpell("ALT-NUMPAD0",Spell_Key("S0")) end

end




--登录游戏初始化
RegisterEvent("PLAYER_LOGIN", function(event)

local CreateMacros = CreateMacros
local CleanKEY = CleanKEY
local SetKEY = SetKEY

CreateMacros()
print("|cffffe00a★Panda★:【|r|c00FF68CC 所有宏文件检测完成 |r|cffffe00a】|r ") 	   
CleanKEY()
print("|cffffe00a★Panda★:【|r|c00FF68CC 登录游戏初始化完成 |r|cffffe00a】|r ") 
SetKEY()


end)

--载入地图初始化
RegisterEvent("PLAYER_ENTERING_WORLD", function(arg1,arg2,arg3,arg4)
local CleanKEY = CleanKEY
local SetKEY = SetKEY

CleanKEY()
print("|cffffe00a★Panda★:【|r|c00FF68CC 加载地图初始化完成 |r|cffffe00a】|r ") 
SetKEY()

end)

--玩家变更了专精的时候
RegisterEvent("PLAYER_SPECIALIZATION_CHANGED", function(arg1,arg2)

local CleanKEY = CleanKEY
local SetKEY = SetKEY

if arg2 == "player" then

CleanKEY()
print("|cffffe00a★Panda★:【|r|c00FF68CC 切换专精初始化完成 |r|cffffe00a】|r ") 
SetKEY()

end 

end)



local Spell_Key = Spell_Key
ns.Spell_Key = Spell_Key
